CBETA – RPN calculator in Fortran
CBETA Function
4 statements
Source File
public function CBETA(X, Y) result(R)
Arguments
Type Intent Optional Attributes Name
complex(kind=wp), intent(in) :: X
complex(kind=wp), intent(in) :: Y
Return Value complex(kind=wp)
Calls
Contents
None
Call graph
cbeta calls cgamma
cgamma calls csch, psi
csch calls csch_c, csch_r