CGAMMA – RPN calculator in Fortran
CGAMMA Function
55 statements
Source File
public function CGAMMA(Z) result(R)
Uses
hyper
Arguments
Type Intent Optional Attributes Name
complex(kind=wp), intent(in) :: Z
Return Value complex(kind=wp)
Calls
Called by
Contents
None
Call graph
cgamma calls csch, psi
csch calls csch_c, csch_r
cbeta calls cgamma