divide – RPN calculator in Fortran
divide Subroutine
29 statements
Source File
private subroutine divide(mode)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: mode
Calls
Called by
Contents
None
Call graph
divide calls isclose, stack, drop_stack, cdrop_stack, rdiv, rdstack, rdrop_stack, rnstack, cstack
drop_stack calls stack
cdrop_stack calls cstack
rdrop_stack calls rdstack, rnstack
eval calls divide, eval
rpn calls eval