EVAL – RPN calculator in Fortran
EVAL Subroutine
3556 statements
Source File
public recursive subroutine EVAL(STR)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: STR
Calls
Called by
Contents
None
Call graph
eval calls eval, csinhc, acoth, acovers, isfrac, push_stack, hav, cuberoot, add, exsec, jinc, cexsec, sinhc, ribesl, hms2h, acot2, hatan, cgamma, tanhc, multiply, tanc, isclose, cacovers, gcd, rdrop_stack, vers, aexsec, crd, beta, csc, stack, clog10, radd, rdstack, rmul, rnint, switch_rat_to_real, besi1, linreg, rnreg, rsub, rybesl, rdiv, rkbesl, isint, rint, asec, covers, cot, rnstack, acsc, cnr, ccovers, bsj, psi, besi0, cmod, sec, sech, drop_stack, cacrd, reg, besk1, cint, print_help, hacos, lcm, creg, rfrac, ctanhc, sinc, acrd, cbeta, besk0, kepler, cvers, rmod, subtract, caexsec, asech, regops, reduce, coth, dec_to_frac, clinreg, rlinreg, acot, rbeta, riemannzeta, cdrop_stack, printx, hasin, frac, cstack, power, avers, csch, acsch, h2hmsd, divide, ahav, bsy0, rdreg, pnr, cavers
csinhc calls isclose
push_stack calls cpush_stack, rpush_stack, push_stack_r
cuberoot calls cuberoot_c, cuberoot_r
add calls rdrop_stack, stack, radd, rdstack, rnstack, drop_stack, cdrop_stack, cstack
sinhc calls isclose
multiply calls rdrop_stack, stack, rdstack, rmul, rnstack, drop_stack, cdrop_stack, cstack
tanc calls tanc_c, tanc_r
rdrop_stack calls rdstack, rnstack
rnint calls rsub, ratnorm, radd
rint calls ratnorm
bsj calls drop_stack, frac, rjbesl
cmod calls cint
drop_stack calls stack
rfrac calls rint, rsub, ratnorm
sinc calls sinc_c, sinc_r
kepler calls reduce
rmod calls rint, rsub, ratnorm, rdiv, rmul
subtract calls rdrop_stack, stack, rdstack, rsub, rnstack, drop_stack, cdrop_stack, cstack
regops calls push_stack, stack, rdstack, rnreg, rnstack, reg, creg, cstack, rdreg
cdrop_stack calls cstack
printx calls cprintx, printx_r, rprintx
frac calls frac_r, frac_c
power calls rdrop_stack, stack, rdstack, switch_rat_to_real, rnstack, drop_stack, cdrop_stack, cstack
divide calls isclose, rdrop_stack, stack, rdstack, rdiv, rnstack, drop_stack, cdrop_stack, cstack
tanc_c calls isclose
cprintx calls isclose
sinc_c calls isclose
rsub calls ratnorm
ratnorm calls gcd
printx_r calls isclose
rprintx calls frac_to_mixed
cpush_stack calls cstack
rpush_stack calls rdstack, rnstack
rdiv calls ratnorm
radd calls ratnorm
sinc_r calls isclose
push_stack_r calls stack
tanc_r calls isclose
rmul calls ratnorm
rpn calls eval