ISREAL – RPN calculator in Fortran
ISREAL Function
119 statements
Source File
public function ISREAL(STR, X) result(NUM_FLAG)
Uses
GLOBAL
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: STR
real(kind=wp), intent(out) :: X
Return Value logical
Calls
Contents
None
Call graph
isreal calls ishex, isdigit, ispm