multiply – RPN calculator in Fortran
multiply Subroutine
21 statements
Source File
private subroutine multiply(mode)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: mode
Calls
Called by
Contents
None
Call graph
multiply calls stack, drop_stack, cdrop_stack, rdstack, rdrop_stack, rmul, rnstack, cstack
drop_stack calls stack
cdrop_stack calls cstack
rdrop_stack calls rdstack, rnstack
eval calls multiply, eval
rpn calls eval