power – RPN calculator in Fortran
power Subroutine
26 statements
Source File
private subroutine power(mode)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: mode
Calls
Called by
Contents
None
Call graph
power calls stack, drop_stack, cdrop_stack, rdstack, rdrop_stack, rnstack, switch_rat_to_real, cstack
drop_stack calls stack
cdrop_stack calls cstack
rdrop_stack calls rdstack, rnstack
eval calls power, eval
rpn calls eval