PRINTX_r – RPN calculator in Fortran
PRINTX_r Subroutine
35 statements
Source File
public subroutine PRINTX_r(X, NUMSTR)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: X
character(len=100), intent(out) :: NUMSTR
Calls
Called by
Contents
None
Call graph
printx_r calls isclose
printx calls printx_r
eval calls printx, eval
rpn calls printx, eval