RATNORM – RPN calculator in Fortran
RATNORM Subroutine
22 statements
Source File
public elemental subroutine RATNORM(NUM, DEN)
Arguments
Type Intent Optional Attributes Name
integer, intent(inout) :: NUM
integer, intent(inout) :: DEN
Calls
Called by
Contents
None
Call graph
ratnorm calls gcd
rmod calls ratnorm, rdiv, rsub, rint, rmul
rdiv calls ratnorm
isrational calls ratnorm
rnint calls ratnorm, rsub, radd
rsub calls ratnorm
frac_to_mixed calls ratnorm
rint calls ratnorm
radd calls ratnorm
rmul calls ratnorm
rbeta calls ratnorm
rfrac calls ratnorm, rsub, rint
eval calls rmod, rnint, rint, rfrac, eval
rlinreg calls rdiv, rsub, rmul
rpn calls eval