RDROP_STACK – RPN calculator in Fortran
RDROP_STACK Subroutine
7 statements
Source File
public subroutine RDROP_STACK(N)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: N
Calls
Called by
Contents
None
Call graph
rdrop_stack calls rnstack, rdstack
power calls rdrop_stack
divide calls rdrop_stack
subtract calls rdrop_stack
eval calls rdrop_stack, power, divide, subtract, eval, add, multiply
add calls rdrop_stack
multiply calls rdrop_stack
rpn calls eval