regops – RPN calculator in Fortran
regops Subroutine
91 statements
Source File
private subroutine regops(str)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str
Calls
Called by
Contents
None
Call graph
regops calls push_stack, stack, rnreg, reg, rdstack, rnstack, rdreg, creg, cstack
push_stack calls rpush_stack, cpush_stack, push_stack_r
rpush_stack calls rdstack, rnstack
cpush_stack calls cstack
push_stack_r calls stack
eval calls regops, eval
rpn calls eval