RLINREG – RPN calculator in Fortran
RLINREG Subroutine
29 statements
Source File
public elemental subroutine RLINREG(NM, DM, NB, DB, R)
Uses
rat
GLOBAL
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: NM
integer, intent(out) :: DM
integer, intent(out) :: NB
integer, intent(out) :: DB
real(kind=wp), intent(out) :: R
Calls
Contents
None
Call graph
rlinreg calls rsub, rmul, rdiv
rsub calls ratnorm
rmul calls ratnorm
rdiv calls ratnorm
ratnorm calls gcd