RMOD – RPN calculator in Fortran
RMOD Subroutine
16 statements
Source File
public elemental subroutine RMOD(N1, D1, N2, D2, NR, DR)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: N1
integer, intent(in) :: D1
integer, intent(in) :: N2
integer, intent(in) :: D2
integer, intent(out) :: NR
integer, intent(out) :: DR
Calls
Called by
Contents
None
Call graph
rmod calls ratnorm, rdiv, rsub, rmul, rint
ratnorm calls gcd
rdiv calls ratnorm
rsub calls ratnorm
rmul calls ratnorm
rint calls ratnorm
eval calls rmod, eval
rpn calls eval