RNINT – RPN calculator in Fortran
RNINT Subroutine
16 statements
Source File
public elemental subroutine RNINT(N, D)
Arguments
Type Intent Optional Attributes Name
integer, intent(inout) :: N
integer, intent(inout) :: D
Calls
Called by
Contents
None
Call graph
rnint calls radd, rsub, ratnorm
radd calls ratnorm
rsub calls ratnorm
ratnorm calls gcd
eval calls rnint, eval
rpn calls eval