csch – RPN calculator in Fortran
csch Interface
3 statements
Source File
public interface csch
Calls
Called by
Contents
Module Procedures
csch_r csch_c
Module Procedures
public elemental function CSCH_r(X) result(Y)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: X
Return Value real(kind=wp)
public elemental function CSCH_c(Z) result(Y)
Arguments
Type Intent Optional Attributes Name
complex(kind=wp), intent(in) :: Z
Return Value complex(kind=wp)
Call graph
csch calls csch_c, csch_r
cgamma calls csch
cbeta calls cgamma