printx – RPN calculator in Fortran
printx Interface
3 statements
Source File
public interface printx
Calls
Called by
Contents
Module Procedures
printx_r cprintx rprintx
Module Procedures
public subroutine PRINTX_r(X, NUMSTR)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: X
character(len=100), intent(out) :: NUMSTR
public subroutine CPRINTX(X, NUMSTR)
Arguments
Type Intent Optional Attributes Name
complex(kind=wp), intent(in) :: X
character(len=100), intent(out) :: NUMSTR
public subroutine RPRINTX(RN, RD, NUMSTR)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: RN
integer, intent(in) :: RD
character(len=100), intent(out) :: NUMSTR
Call graph
printx calls printx_r, rprintx, cprintx
printx_r calls isclose
rprintx calls frac_to_mixed
cprintx calls isclose
eval calls printx, eval
rpn calls printx, eval