push_stack – RPN calculator in Fortran
push_stack Interface
3 statements
Source File
public interface push_stack
Calls
Called by
Contents
Module Procedures
push_stack_r cpush_stack rpush_stack
Module Procedures
public subroutine PUSH_STACK_r(X)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: X
public subroutine CPUSH_STACK(X)
Arguments
Type Intent Optional Attributes Name
complex(kind=wp), intent(in) :: X
public subroutine RPUSH_STACK(RN, RD)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: RN
integer, intent(in) :: RD
Call graph
push_stack calls rpush_stack, cpush_stack, push_stack_r
rpush_stack calls rnstack, rdstack
cpush_stack calls cstack
push_stack_r calls stack
eval calls push_stack, eval, regops
rpn calls push_stack, eval
regops calls push_stack