RPN – RPN calculator in Fortran
RPN Program
127 statements
Source File
Uses
funcs
iso_fortran_env
GLOBAL
stackops
evals
Calls
Contents
Variables
PI TWOPI IDX IERR DEL PTR RN RD X CX LINE SUBSTR NUMSTR NUM_FLAG
Variables
Type Attributes Name Initial
real(kind=wp), parameter :: PI = 4._wp*atan(1._wp)
real(kind=wp), parameter :: TWOPI = 2*pi
integer :: IDX
integer :: IERR
integer :: DEL
integer :: PTR
integer :: RN
integer :: RD
real(kind=wp) :: X
complex(kind=wp) :: CX
character(len=300) :: LINE
character(len=300) :: SUBSTR
character(len=100) :: NUMSTR
logical :: NUM_FLAG = .false.
Call graph
rpn calls push_stack, stack, iscomplex, rdstack, isreal, eval, isrational, printx, rnstack, toupper, init_stack, cstack
push_stack calls cpush_stack, rpush_stack, push_stack_r
eval calls push_stack, stack, rdstack, eval, printx, rnstack, cstack, csinhc, acoth, acovers, isfrac, hav, cuberoot, add, exsec, jinc, cexsec, sinhc, ribesl, hms2h, acot2, hatan, cgamma, tanhc, multiply, tanc, isclose, cacovers, gcd, rdrop_stack, vers, aexsec, crd, beta, csc, clog10, radd, rmul, rnint, switch_rat_to_real, besi1, linreg, rnreg, rsub, rybesl, rdiv, rkbesl, isint, rint, asec, covers, cot, acsc, cnr, ccovers, bsj, psi, besi0, cmod, sec, sech, drop_stack, cacrd, reg, besk1, cint, print_help, hacos, lcm, creg, rfrac, ctanhc, sinc, acrd, cbeta, besk0, kepler, cvers, rmod, subtract, caexsec, asech, regops, reduce, coth, dec_to_frac, clinreg, rlinreg, acot, rbeta, riemannzeta, cdrop_stack, hasin, frac, power, avers, csch, acsch, h2hmsd, divide, ahav, bsy0, rdreg, pnr, cavers
printx calls printx_r, cprintx, rprintx
csinhc calls isclose
cuberoot calls cuberoot_c, cuberoot_r
add calls stack, rdstack, rnstack, cstack, rdrop_stack, radd, drop_stack, cdrop_stack
sinhc calls isclose
multiply calls stack, rdstack, rnstack, cstack, rdrop_stack, rmul, drop_stack, cdrop_stack
tanc calls tanc_c, tanc_r
rdrop_stack calls rdstack, rnstack
rnint calls ratnorm, rsub, radd
printx_r calls isclose
rint calls ratnorm
bsj calls drop_stack, frac, rjbesl
cprintx calls isclose
cmod calls cint
drop_stack calls stack
rfrac calls rint, ratnorm, rsub
cpush_stack calls cstack
rpush_stack calls rdstack, rnstack
sinc calls sinc_c, sinc_r
push_stack_r calls stack
kepler calls reduce
rmod calls rint, ratnorm, rdiv, rsub, rmul
subtract calls stack, rdstack, rnstack, cstack, rdrop_stack, rsub, drop_stack, cdrop_stack
regops calls push_stack, stack, rdstack, rnstack, cstack, rnreg, reg, creg, rdreg
rprintx calls frac_to_mixed
cdrop_stack calls cstack
frac calls frac_r, frac_c
power calls stack, rdstack, rnstack, cstack, rdrop_stack, switch_rat_to_real, drop_stack, cdrop_stack
divide calls stack, rdstack, rnstack, cstack, isclose, rdrop_stack, rdiv, drop_stack, cdrop_stack
tanc_c calls isclose
ratnorm calls gcd
sinc_c calls isclose
rdiv calls ratnorm
rsub calls ratnorm
rmul calls ratnorm
radd calls ratnorm
tanc_r calls isclose
sinc_r calls isclose